/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:69c26390-1284-44d2-a66c-2467e7d4153b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2iSfgDTDx",
    "aws_user_pools_web_client_id": "n69sv2tfpqoru7kjc3amublb",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://fej3shjhxzgj5fhsg7xk33kyhi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-e3djtem35vhrtactujr2jzec6m",
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "AroundTownMap-staging": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "AroundTownMap-staging"
            }
        }
    }
};


export default awsmobile;
